### ISSUE TITLE
problems with text editor, empty lines not showing

### ISSUE THREAD

**Issue by idoheinemann** [erikik8090/erikik8090.github.io#1]
the text editor skips over empty lines and does not show them. when I tried to write a comment at the end of the survivor code the text jumped above.

**Comment by idoheinemann** [comment]
a correction on this problem: this only happens when the last line is not empty.

**Comment by idoheinemann** [comment]
another correction: this happens when the compiler throws a warning, problem or debug information of any kind

**Comment by erikik8090** [comment]
Ported the issue to the right repo
 https://github.com/westerndigitalcorporation/corewars-risc-v/issues/18
